name: workout_selector
description: Project to select workouts.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.0
  freezed_annotation: ^2.0.0
  get_it: ^7.0.0
  hive: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.0.0
  path_provider: ^2.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0


